apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: tradingbot-debug-patch.yaml
    target:
      kind: Deployment
      name: tradingbot
  - path: tradingbot-svc-debug-patch.yaml
    target:
      kind: Service
      name: tradingbot
