apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tradingbot.yaml
configMapGenerator:
  - name: tradingbot-config
    files:
      - config.yaml=../../../../configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
