apiVersion: v1
kind: Service
metadata:
  name: tradingbot
spec:
  ports:
    - name: http
      port: 8000
    - name: grpc
      port: 9000
  selector:
    app: tradingbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingbot
spec:
  selector:
    matchLabels:
      app: tradingbot
  template:
    metadata:
      labels:
        app: tradingbot
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tradingbot"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: tradingbot
          image: tradingbot
          ports:
            - containerPort: 8000
            - containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: /data/conf
      volumes:
        - name: config
          configMap:
            name: tradingbot-config
