// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tradingbot/app/tradingbot/internal/data/ent/greeter"
	"tradingbot/app/tradingbot/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreeterUpdate is the builder for updating Greeter entities.
type GreeterUpdate struct {
	config
	hooks    []Hook
	mutation *GreeterMutation
}

// Where appends a list predicates to the GreeterUpdate builder.
func (_u *GreeterUpdate) Where(ps ...predicate.Greeter) *GreeterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHello sets the "hello" field.
func (_u *GreeterUpdate) SetHello(v string) *GreeterUpdate {
	_u.mutation.SetHello(v)
	return _u
}

// SetNillableHello sets the "hello" field if the given value is not nil.
func (_u *GreeterUpdate) SetNillableHello(v *string) *GreeterUpdate {
	if v != nil {
		_u.SetHello(*v)
	}
	return _u
}

// Mutation returns the GreeterMutation object of the builder.
func (_u *GreeterUpdate) Mutation() *GreeterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GreeterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreeterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GreeterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreeterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GreeterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(greeter.Table, greeter.Columns, sqlgraph.NewFieldSpec(greeter.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hello(); ok {
		_spec.SetField(greeter.FieldHello, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greeter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GreeterUpdateOne is the builder for updating a single Greeter entity.
type GreeterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GreeterMutation
}

// SetHello sets the "hello" field.
func (_u *GreeterUpdateOne) SetHello(v string) *GreeterUpdateOne {
	_u.mutation.SetHello(v)
	return _u
}

// SetNillableHello sets the "hello" field if the given value is not nil.
func (_u *GreeterUpdateOne) SetNillableHello(v *string) *GreeterUpdateOne {
	if v != nil {
		_u.SetHello(*v)
	}
	return _u
}

// Mutation returns the GreeterMutation object of the builder.
func (_u *GreeterUpdateOne) Mutation() *GreeterMutation {
	return _u.mutation
}

// Where appends a list predicates to the GreeterUpdate builder.
func (_u *GreeterUpdateOne) Where(ps ...predicate.Greeter) *GreeterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GreeterUpdateOne) Select(field string, fields ...string) *GreeterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Greeter entity.
func (_u *GreeterUpdateOne) Save(ctx context.Context) (*Greeter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreeterUpdateOne) SaveX(ctx context.Context) *Greeter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GreeterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreeterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GreeterUpdateOne) sqlSave(ctx context.Context) (_node *Greeter, err error) {
	_spec := sqlgraph.NewUpdateSpec(greeter.Table, greeter.Columns, sqlgraph.NewFieldSpec(greeter.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Greeter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, greeter.FieldID)
		for _, f := range fields {
			if !greeter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != greeter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hello(); ok {
		_spec.SetField(greeter.FieldHello, field.TypeString, value)
	}
	_node = &Greeter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greeter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
