// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: trading/v1/strategy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_trading_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_trading_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

type RunSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Placed        int32                  `protobuf:"varint,4,opt,name=placed,proto3" json:"placed,omitempty"`
	Filled        int32                  `protobuf:"varint,5,opt,name=filled,proto3" json:"filled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_trading_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_trading_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *RunSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSummary) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *RunSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunSummary) GetPlaced() int32 {
	if x != nil {
		return x.Placed
	}
	return 0
}

func (x *RunSummary) GetFilled() int32 {
	if x != nil {
		return x.Filled
	}
	return 0
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Runs          []*RunSummary          `protobuf:"bytes,2,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_trading_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_trading_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *StatusReply) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StatusReply) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

var File_trading_v1_strategy_proto protoreflect.FileDescriptor

const file_trading_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x19trading/v1/strategy.proto\x12\n" +
	"trading.v1\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\"{\n" +
	"\n" +
	"RunSummary\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06placed\x18\x04 \x01(\x05R\x06placed\x12\x16\n" +
	"\x06filled\x18\x05 \x01(\x05R\x06filled\"Z\n" +
	"\vStatusReply\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12*\n" +
	"\x04runs\x18\x02 \x03(\v2\x16.trading.v1.RunSummaryR\x04runs2|\n" +
	"\x0fStrategyService\x12i\n" +
	"\x06Status\x12\x19.trading.v1.StatusRequest\x1a\x17.trading.v1.StatusReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/strategies/{strategy_id}/statusB-Z+tradingbot/app/tradingbot/api/trading/v1;v1b\x06proto3"

var (
	file_trading_v1_strategy_proto_rawDescOnce sync.Once
	file_trading_v1_strategy_proto_rawDescData []byte
)

func file_trading_v1_strategy_proto_rawDescGZIP() []byte {
	file_trading_v1_strategy_proto_rawDescOnce.Do(func() {
		file_trading_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_v1_strategy_proto_rawDesc), len(file_trading_v1_strategy_proto_rawDesc)))
	})
	return file_trading_v1_strategy_proto_rawDescData
}

var file_trading_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trading_v1_strategy_proto_goTypes = []any{
	(*StatusRequest)(nil), // 0: trading.v1.StatusRequest
	(*RunSummary)(nil),    // 1: trading.v1.RunSummary
	(*StatusReply)(nil),   // 2: trading.v1.StatusReply
}
var file_trading_v1_strategy_proto_depIdxs = []int32{
	1, // 0: trading.v1.StatusReply.runs:type_name -> trading.v1.RunSummary
	0, // 1: trading.v1.StrategyService.Status:input_type -> trading.v1.StatusRequest
	2, // 2: trading.v1.StrategyService.Status:output_type -> trading.v1.StatusReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trading_v1_strategy_proto_init() }
func file_trading_v1_strategy_proto_init() {
	if File_trading_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_v1_strategy_proto_rawDesc), len(file_trading_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_v1_strategy_proto_goTypes,
		DependencyIndexes: file_trading_v1_strategy_proto_depIdxs,
		MessageInfos:      file_trading_v1_strategy_proto_msgTypes,
	}.Build()
	File_trading_v1_strategy_proto = out.File
	file_trading_v1_strategy_proto_goTypes = nil
	file_trading_v1_strategy_proto_depIdxs = nil
}
