// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: trading/v1/strategy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStrategyServiceStatus = "/trading.v1.StrategyService/Status"

type StrategyServiceHTTPServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterStrategyServiceHTTPServer(s *http.Server, srv StrategyServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/strategies/{strategy_id}/status", _StrategyService_Status0_HTTP_Handler(srv))
}

func _StrategyService_Status0_HTTP_Handler(srv StrategyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyServiceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Status(ctx, req.(*StatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatusReply)
		return ctx.Result(200, reply)
	}
}

type StrategyServiceHTTPClient interface {
	Status(ctx context.Context, req *StatusRequest, opts ...http.CallOption) (rsp *StatusReply, err error)
}

type StrategyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStrategyServiceHTTPClient(client *http.Client) StrategyServiceHTTPClient {
	return &StrategyServiceHTTPClientImpl{client}
}

func (c *StrategyServiceHTTPClientImpl) Status(ctx context.Context, in *StatusRequest, opts ...http.CallOption) (*StatusReply, error) {
	var out StatusReply
	pattern := "/v1/strategies/{strategy_id}/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyServiceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
