using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct Multiplier
{
    // 20x is the sanity cap; actual operational cap is MaxMultiplierCap in config
    private const decimal MaxReasonableMultiplier = 20m;

    private static Validation Validate(decimal value) =>
        value > 0 && value <= MaxReasonableMultiplier
            ? Validation.Ok
            : Validation.Invalid($"Multiplier must be between 0 (exclusive) and {MaxReasonableMultiplier} (inclusive)");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(Multiplier left, Multiplier right) => left.Value < right.Value;
    public static bool operator >(Multiplier left, Multiplier right) => left.Value > right.Value;
    public static bool operator <=(Multiplier left, Multiplier right) => left.Value <= right.Value;
    public static bool operator >=(Multiplier left, Multiplier right) => left.Value >= right.Value;

    // Multiplier + Multiplier = Multiplier (additive bear boost: tierMultiplier + bearBoost)
    public static Multiplier operator +(Multiplier left, Multiplier right) =>
        Multiplier.From(left.Value + right.Value);
}
