using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct Percentage
{
    // 0-1 format: 0.05 = 5%. Multiply by 100 for display.
    private static Validation Validate(decimal value) =>
        value >= 0 && value <= 1
            ? Validation.Ok
            : Validation.Invalid("Percentage must be between 0 and 1 (e.g. 0.05 for 5%)");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(Percentage left, Percentage right) => left.Value < right.Value;
    public static bool operator >(Percentage left, Percentage right) => left.Value > right.Value;
    public static bool operator <=(Percentage left, Percentage right) => left.Value <= right.Value;
    public static bool operator >=(Percentage left, Percentage right) => left.Value >= right.Value;
}
