using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct Price
{
    private static Validation Validate(decimal value) =>
        value > 0
            ? Validation.Ok
            : Validation.Invalid("Price must be strictly positive (> 0)");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(Price left, Price right) => left.Value < right.Value;
    public static bool operator >(Price left, Price right) => left.Value > right.Value;
    public static bool operator <=(Price left, Price right) => left.Value <= right.Value;
    public static bool operator >=(Price left, Price right) => left.Value >= right.Value;
}
