using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct Quantity
{
    // Zero allowed: Purchase records start at 0 quantity before order fill
    private static Validation Validate(decimal value) =>
        value >= 0
            ? Validation.Ok
            : Validation.Invalid("Quantity must be zero or positive");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(Quantity left, Quantity right) => left.Value < right.Value;
    public static bool operator >(Quantity left, Quantity right) => left.Value > right.Value;
    public static bool operator <=(Quantity left, Quantity right) => left.Value <= right.Value;
    public static bool operator >=(Quantity left, Quantity right) => left.Value >= right.Value;

    // Cross-type: Quantity * Price = UsdAmount (cost of purchase)
    public static UsdAmount operator *(Quantity quantity, Price price) =>
        UsdAmount.From(quantity.Value * price.Value);

    // Quantity + Quantity = Quantity (accumulation)
    public static Quantity operator +(Quantity left, Quantity right) =>
        Quantity.From(left.Value + right.Value);
}
