using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct UsdAmount
{
    private static Validation Validate(decimal value) =>
        value > 0
            ? Validation.Ok
            : Validation.Invalid("UsdAmount must be strictly positive (> 0)");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(UsdAmount left, UsdAmount right) => left.Value < right.Value;
    public static bool operator >(UsdAmount left, UsdAmount right) => left.Value > right.Value;
    public static bool operator <=(UsdAmount left, UsdAmount right) => left.Value <= right.Value;
    public static bool operator >=(UsdAmount left, UsdAmount right) => left.Value >= right.Value;

    // Arithmetic: UsdAmount + UsdAmount = UsdAmount (accumulation in portfolio)
    public static UsdAmount operator +(UsdAmount left, UsdAmount right) =>
        UsdAmount.From(left.Value + right.Value);

    // Cross-type: UsdAmount * Multiplier = UsdAmount (applying DCA boost)
    public static UsdAmount operator *(UsdAmount amount, Multiplier multiplier) =>
        UsdAmount.From(amount.Value * multiplier.Value);

    // Cross-type: UsdAmount / Price = Quantity (how much BTC can I buy?)
    public static Quantity operator /(UsdAmount amount, Price price) =>
        Quantity.From(amount.Value / price.Value);
}
