using Vogen;

namespace TradingBot.ApiService.Models.Values;

[ValueObject<decimal>]
public readonly partial struct VndAmount
{
    private static Validation Validate(decimal value) =>
        value >= 0
            ? Validation.Ok
            : Validation.Invalid("VndAmount must be non-negative");

    // Comparison operators (NOT generated by Vogen)
    public static bool operator <(VndAmount left, VndAmount right) => left.Value < right.Value;
    public static bool operator >(VndAmount left, VndAmount right) => left.Value > right.Value;
    public static bool operator <=(VndAmount left, VndAmount right) => left.Value <= right.Value;
    public static bool operator >=(VndAmount left, VndAmount right) => left.Value >= right.Value;

    // Arithmetic: VndAmount + VndAmount = VndAmount (accumulation in portfolio)
    public static VndAmount operator +(VndAmount left, VndAmount right) =>
        VndAmount.From(left.Value + right.Value);
}
