// Code generated by ent, DO NOT EDIT.

package greeter

import (
	"tradingbot/app/tradingbot/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Greeter {
	return predicate.Greeter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Greeter {
	return predicate.Greeter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Greeter {
	return predicate.Greeter(sql.FieldLTE(FieldID, id))
}

// Hello applies equality check predicate on the "hello" field. It's identical to HelloEQ.
func Hello(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldEQ(FieldHello, v))
}

// HelloEQ applies the EQ predicate on the "hello" field.
func HelloEQ(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldEQ(FieldHello, v))
}

// HelloNEQ applies the NEQ predicate on the "hello" field.
func HelloNEQ(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldNEQ(FieldHello, v))
}

// HelloIn applies the In predicate on the "hello" field.
func HelloIn(vs ...string) predicate.Greeter {
	return predicate.Greeter(sql.FieldIn(FieldHello, vs...))
}

// HelloNotIn applies the NotIn predicate on the "hello" field.
func HelloNotIn(vs ...string) predicate.Greeter {
	return predicate.Greeter(sql.FieldNotIn(FieldHello, vs...))
}

// HelloGT applies the GT predicate on the "hello" field.
func HelloGT(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldGT(FieldHello, v))
}

// HelloGTE applies the GTE predicate on the "hello" field.
func HelloGTE(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldGTE(FieldHello, v))
}

// HelloLT applies the LT predicate on the "hello" field.
func HelloLT(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldLT(FieldHello, v))
}

// HelloLTE applies the LTE predicate on the "hello" field.
func HelloLTE(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldLTE(FieldHello, v))
}

// HelloContains applies the Contains predicate on the "hello" field.
func HelloContains(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldContains(FieldHello, v))
}

// HelloHasPrefix applies the HasPrefix predicate on the "hello" field.
func HelloHasPrefix(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldHasPrefix(FieldHello, v))
}

// HelloHasSuffix applies the HasSuffix predicate on the "hello" field.
func HelloHasSuffix(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldHasSuffix(FieldHello, v))
}

// HelloEqualFold applies the EqualFold predicate on the "hello" field.
func HelloEqualFold(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldEqualFold(FieldHello, v))
}

// HelloContainsFold applies the ContainsFold predicate on the "hello" field.
func HelloContainsFold(v string) predicate.Greeter {
	return predicate.Greeter(sql.FieldContainsFold(FieldHello, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Greeter) predicate.Greeter {
	return predicate.Greeter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Greeter) predicate.Greeter {
	return predicate.Greeter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Greeter) predicate.Greeter {
	return predicate.Greeter(sql.NotPredicates(p))
}
