// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tradingbot/app/tradingbot/internal/biz"
	"tradingbot/app/tradingbot/internal/conf"
	"tradingbot/app/tradingbot/internal/data"
	"tradingbot/app/tradingbot/internal/data/hyperliquid"
	"tradingbot/app/tradingbot/internal/server"
	"tradingbot/app/tradingbot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	redisClient, cleanup2, err := data.NewRedisClient(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	strategyStateRepo := data.NewStrategyStateRepo(redisClient, logger)
	strategyService := service.NewStrategyService(strategyStateRepo, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, strategyService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, strategyService, logger)
	exchangeConf := newExchangeConf(bootstrap)
	ctx := context.Background()
	hlEx, err := hyperliquid.NewHyperliquidExchange(ctx, exchangeConf, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	var exchange biz.Exchange = hlEx
	cloidDeriver := hyperliquid.NewCloidDeriver()
	recursiveBuyUsecase := biz.NewRecursiveBuyUsecase(exchange, strategyStateRepo, cloidDeriver, logger)
	strategies := server.NewStrategies(bootstrap)
	scheduler := server.NewSchedulerServer(strategies, recursiveBuyUsecase, logger)
	app := newApp(logger, grpcServer, httpServer, scheduler)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
