// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/tradingbot/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Exchange      *Exchange              `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Strategies    []*Strategy            `protobuf:"bytes,4,rep,name=strategies,proto3" json:"strategies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetExchange() *Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

func (x *Bootstrap) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hyperliquid   *Exchange_Hyperliquid  `protobuf:"bytes,1,opt,name=hyperliquid,proto3" json:"hyperliquid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Exchange) GetHyperliquid() *Exchange_Hyperliquid {
	if x != nil {
		return x.Hyperliquid
	}
	return nil
}

type Strategy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coin            string                 `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	QuoteAmount     string                 `protobuf:"bytes,3,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	Interval        *durationpb.Duration   `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	LadderSize      int32                  `protobuf:"varint,5,opt,name=ladder_size,json=ladderSize,proto3" json:"ladder_size,omitempty"`
	PriceOffsetsBps []string               `protobuf:"bytes,6,rep,name=price_offsets_bps,json=priceOffsetsBps,proto3" json:"price_offsets_bps,omitempty"`
	MaxSlippageBps  string                 `protobuf:"bytes,7,opt,name=max_slippage_bps,json=maxSlippageBps,proto3" json:"max_slippage_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Strategy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Strategy) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *Strategy) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *Strategy) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Strategy) GetLadderSize() int32 {
	if x != nil {
		return x.LadderSize
	}
	return 0
}

func (x *Strategy) GetPriceOffsetsBps() []string {
	if x != nil {
		return x.PriceOffsetsBps
	}
	return nil
}

func (x *Strategy) GetMaxSlippageBps() string {
	if x != nil {
		return x.MaxSlippageBps
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Dapr          *Server_Dapr           `protobuf:"bytes,3,opt,name=dapr,proto3" json:"dapr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetDapr() *Server_Dapr {
	if x != nil {
		return x.Dapr
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Pubsub        *Data_Pubsub           `protobuf:"bytes,3,opt,name=pubsub,proto3" json:"pubsub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetPubsub() *Data_Pubsub {
	if x != nil {
		return x.Pubsub
	}
	return nil
}

type Exchange_Hyperliquid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUrl        string                 `protobuf:"bytes,1,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	MasterAddress string                 `protobuf:"bytes,2,opt,name=master_address,json=masterAddress,proto3" json:"master_address,omitempty"`
	AgentKeyEnv   string                 `protobuf:"bytes,3,opt,name=agent_key_env,json=agentKeyEnv,proto3" json:"agent_key_env,omitempty"`
	Testnet       bool                   `protobuf:"varint,4,opt,name=testnet,proto3" json:"testnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange_Hyperliquid) Reset() {
	*x = Exchange_Hyperliquid{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange_Hyperliquid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange_Hyperliquid) ProtoMessage() {}

func (x *Exchange_Hyperliquid) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange_Hyperliquid.ProtoReflect.Descriptor instead.
func (*Exchange_Hyperliquid) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Exchange_Hyperliquid) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *Exchange_Hyperliquid) GetMasterAddress() string {
	if x != nil {
		return x.MasterAddress
	}
	return ""
}

func (x *Exchange_Hyperliquid) GetAgentKeyEnv() string {
	if x != nil {
		return x.AgentKeyEnv
	}
	return ""
}

func (x *Exchange_Hyperliquid) GetTestnet() bool {
	if x != nil {
		return x.Testnet
	}
	return false
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Dapr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Dapr) Reset() {
	*x = Server_Dapr{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Dapr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Dapr) ProtoMessage() {}

func (x *Server_Dapr) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Dapr.ProtoReflect.Descriptor instead.
func (*Server_Dapr) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Server_Dapr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Dapr) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Pubsub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Pubsub) Reset() {
	*x = Data_Pubsub{}
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Pubsub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Pubsub) ProtoMessage() {}

func (x *Data_Pubsub) ProtoReflect() protoreflect.Message {
	mi := &file_app_tradingbot_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Pubsub.ProtoReflect.Descriptor instead.
func (*Data_Pubsub) Descriptor() ([]byte, []int) {
	return file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Data_Pubsub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data_Pubsub) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var File_app_tradingbot_internal_conf_conf_proto protoreflect.FileDescriptor

const file_app_tradingbot_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"'app/tradingbot/internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xc5\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x120\n" +
	"\bexchange\x18\x03 \x01(\v2\x14.kratos.api.ExchangeR\bexchange\x124\n" +
	"\n" +
	"strategies\x18\x04 \x03(\v2\x14.kratos.api.StrategyR\n" +
	"strategies\"\xdc\x01\n" +
	"\bExchange\x12B\n" +
	"\vhyperliquid\x18\x01 \x01(\v2 .kratos.api.Exchange.HyperliquidR\vhyperliquid\x1a\x8b\x01\n" +
	"\vHyperliquid\x12\x17\n" +
	"\aapi_url\x18\x01 \x01(\tR\x06apiUrl\x12%\n" +
	"\x0emaster_address\x18\x02 \x01(\tR\rmasterAddress\x12\"\n" +
	"\ragent_key_env\x18\x03 \x01(\tR\vagentKeyEnv\x12\x18\n" +
	"\atestnet\x18\x04 \x01(\bR\atestnet\"\xff\x01\n" +
	"\bStrategy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\tR\x04coin\x12!\n" +
	"\fquote_amount\x18\x03 \x01(\tR\vquoteAmount\x125\n" +
	"\binterval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12\x1f\n" +
	"\vladder_size\x18\x05 \x01(\x05R\n" +
	"ladderSize\x12*\n" +
	"\x11price_offsets_bps\x18\x06 \x03(\tR\x0fpriceOffsetsBps\x12(\n" +
	"\x10max_slippage_bps\x18\a \x01(\tR\x0emaxSlippageBps\"\x98\x03\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12+\n" +
	"\x04dapr\x18\x03 \x01(\v2\x17.kratos.api.Server.DaprR\x04dapr\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a1\n" +
	"\x04Dapr\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"\xc2\x03\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12/\n" +
	"\x06pubsub\x18\x03 \x01(\v2\x17.kratos.api.Data.PubsubR\x06pubsub\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1a2\n" +
	"\x06Pubsub\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topicB.Z,tradingbot/app/tradingbot/internal/conf;confb\x06proto3"

var (
	file_app_tradingbot_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_tradingbot_internal_conf_conf_proto_rawDescData []byte
)

func file_app_tradingbot_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_tradingbot_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_tradingbot_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_tradingbot_internal_conf_conf_proto_rawDesc), len(file_app_tradingbot_internal_conf_conf_proto_rawDesc)))
	})
	return file_app_tradingbot_internal_conf_conf_proto_rawDescData
}

var file_app_tradingbot_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_tradingbot_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),            // 0: kratos.api.Bootstrap
	(*Exchange)(nil),             // 1: kratos.api.Exchange
	(*Strategy)(nil),             // 2: kratos.api.Strategy
	(*Server)(nil),               // 3: kratos.api.Server
	(*Data)(nil),                 // 4: kratos.api.Data
	(*Exchange_Hyperliquid)(nil), // 5: kratos.api.Exchange.Hyperliquid
	(*Server_HTTP)(nil),          // 6: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),          // 7: kratos.api.Server.GRPC
	(*Server_Dapr)(nil),          // 8: kratos.api.Server.Dapr
	(*Data_Database)(nil),        // 9: kratos.api.Data.Database
	(*Data_Redis)(nil),           // 10: kratos.api.Data.Redis
	(*Data_Pubsub)(nil),          // 11: kratos.api.Data.Pubsub
	(*durationpb.Duration)(nil),  // 12: google.protobuf.Duration
}
var file_app_tradingbot_internal_conf_conf_proto_depIdxs = []int32{
	3,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	4,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	1,  // 2: kratos.api.Bootstrap.exchange:type_name -> kratos.api.Exchange
	2,  // 3: kratos.api.Bootstrap.strategies:type_name -> kratos.api.Strategy
	5,  // 4: kratos.api.Exchange.hyperliquid:type_name -> kratos.api.Exchange.Hyperliquid
	12, // 5: kratos.api.Strategy.interval:type_name -> google.protobuf.Duration
	6,  // 6: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	7,  // 7: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	8,  // 8: kratos.api.Server.dapr:type_name -> kratos.api.Server.Dapr
	9,  // 9: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	10, // 10: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	11, // 11: kratos.api.Data.pubsub:type_name -> kratos.api.Data.Pubsub
	12, // 12: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	12, // 13: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	12, // 14: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	12, // 15: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_app_tradingbot_internal_conf_conf_proto_init() }
func file_app_tradingbot_internal_conf_conf_proto_init() {
	if File_app_tradingbot_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_tradingbot_internal_conf_conf_proto_rawDesc), len(file_app_tradingbot_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_tradingbot_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_tradingbot_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_tradingbot_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_tradingbot_internal_conf_conf_proto = out.File
	file_app_tradingbot_internal_conf_conf_proto_goTypes = nil
	file_app_tradingbot_internal_conf_conf_proto_depIdxs = nil
}
