apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  DATABASE_CONNECTION_STRING: "host=postgres port=5432 user=tradingbot password=tradingbot dbname=tradingbot sslmode=disable"
  REDIS_HOST: "redis:6379"
  REDIS_PASSWORD: ""
